# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e24ca97116efdca1bcbff082036a7e96d2f0e317ce2224c6520187d987c26c22e3fd73ce296a336a0fcf93ba1a542398ab3ca2c24f606ef33f5b01231270b59b

test:
  secret_key_base: 96653e19b03cf2b4b4bd61756d60b569e19c4dd7a13c849a13889e26ca70b14199edde35aa9ebb59f725d7b02bba99677fc7ed65c58e2f30c2f3060b7259284e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
